title: The Aesthetic Edit
description: Curated recommendations for your tech workspace, home decor, and daily style.
url: "[https://theaestheticedit.me](https://theaestheticedit.me)" # Update this to your GitHub URL or custom domain
author: Sourabh
timezone: Asia/Kolkata

# These native plugins automatically handle SEO, Pinterest Rich Pins, and Sitemaps.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title/